### ISSUE TITLE
Drop rustc-serialize dependency

### ISSUE THREAD

**Issue by dtolnay** [InsidiousMind/EveOnlineMarketFinder#1]
It has been deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

Is there any functionality you would require from another library before this would be possible?

**Comment by insipx** [comment]
Woah, you found my repo! @dtolnay 

Fortunately, rustc was used in a previous iteration of this project (though, this project is only a few days old) here: https://github.com/InsidiousMind/EveOnlineMarketFinder/blob/old_csv/src/parse.rs#L3

I see there is a rogue `extern crate rustc;` floating around in main.rs. I believe I will be able to get rid of this promptly :-)

So, i don't believe there is any functionality I will require from another library. Though I am not sure how the csv module will work without rustc.

**Comment by dtolnay** [comment]
Oh the csv crate is being rewritten to use Serde. This may be a bad time to write a ton of rustc-serialize code around it. See here for progress: https://github.com/BurntSushi/rust-csv/issues/29#issuecomment-296848620. There is a work in progress branch that may or may not be complete enough to depend on right now.

**Comment by insipx** [comment]
Ahok cool! Thanks for the warning. Since I'm no longer using the CSV module and opting to instead use an API that accomplishes the same thing, I will be OK for the foreseeable future, and don't use any other libraries utilizing Rustc.

**Comment by dtolnay** [comment]
Does that mean this dependency can be removed? [`Cargo.toml#L13`](https://github.com/InsidiousMind/EveOnlineMarketFinder/blob/24f84a1a349d9440ca8434a98b71cb05e5a903ca/Cargo.toml#L13)

**Comment by insipx** [comment]
Yep,
Removed it
